version: "3.1"
services:
    yamakanban_db:
        image: postgres
        hostname: yamakanban_db
        container_name: yamakanban_db
        restart: unless-stopped
        volumes:
            - sql:/var/lib/postgresql/data
        env_file:
            - "production.env"
        ports:
            - "5432:5432"
    yamakanban_redis:
        image: redis
        hostname: "yamakanban_redis"
        ports: 
            - "6379:6379"
        volumes:
            - redis_cache:/data
    yamakanban:
        restart: unless-stopped
        command: ./boot.sh
        hostname: yamakanban
        container_name: yamakanban
        build:
            context: .
            dockerfile: ./dockerfile
        volumes:
            - yamakanban_data:/root/data
        env_file:
            - "production.env"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - yamakanban_db
            - yamakanban_redis
        links:
            - yamakanban_db
            - yamakanban_redis
volumes:
    sql:
        driver: local
    yamakanban_data:
        driver: local
    redis_cache:
        driver: local
