version: "3.1"
services:
    yamakanban_db:
        image: postgres
        hostname: yamakanban_db
        container_name: yamakanban_db
        volumes:
            - sql:/var/lib/postgresql/data
        env_file:
            - "development.env"
        ports:
            - "5432:5432"
    yamakanban_redis:
        image: redis
        hostname: "yamakanban_redis"
        ports: 
            - "6379:6379"
        volumes:
            - redis_cache:/data
volumes:
    sql:
        driver: local
    redis_cache:
        driver: local
