version: "3.1"
services:
    todoman_db:
        image: postgres
        hostname: todoman_db
        container_name: todoman_db
        restart: unless-stopped
        volumes:
            - sql:/var/lib/postgresql/data
        env_file:
            - "development.env"
        ports:
            - "5432:5432"
volumes:
    sql:
        driver: local
