version: "3.1"
services:
    yamakanban_db:
        image: postgres
        hostname: yamakanban_db
        container_name: yamakanban_db
        volumes:
            - sql:/var/lib/postgresql/data
        env_file:
            - "development.env"
        ports:
            - "5432:5432"
volumes:
    sql:
        driver: local
